[[plugins]]
repo = 'Shougo/dein.vim'


[[plugins]]
repo = 'Shougo/ddc.vim'
[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'Shougo/ddc-around'
[[plugins]]
repo = 'Shougo/ddc-matcher_head'
[[plugins]]
repo = 'Shougo/ddc-sorter_rank'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'scrooloose/nerdcommenter'
[[plugins]]
repo = 'mattn/emmet-vim'
[[plugins]]
repo = 'vim-scripts/YankRing.vim'
[[plugins]]
repo = 'mbbill/undotree'
[[plugins]]
repo = 'kana/vim-textobj-user'
[[plugins]]
repo = 'h1mesuke/textobj-wiw'
[[plugins]]
repo = 'tpope/vim-surround'
[[plugins]]
repo = 'gcmt/wildfire.vim'
[[plugins]]
repo = 'othree/html5.vim'
[[plugins]]
repo = 'haya14busa/vim-migemo'
[[plugins]]
repo = 'editorconfig/editorconfig-vim'
[[plugins]]
repo = 'unblevable/quick-scope'


[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
# カーソル位置のコンテキストに合わせてftを切り替える
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]]
repo = 'Shougo/context_filetype.vim'
[[plugins]]
repo = 'Shougo/neco-syntax'

[[plugins]]
## C言語用
repo =  'Rip-Rip/clang_complete'
on_ft = ["c", "cpp"]
hook_add = '''
let g:clang_library_path="/usr/local/opt/llvm/lib"
'''

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['js','javascript']

[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = ['ruby']
[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['md']

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['md']


