[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'vim-jp/vital.vim'
[[plugins]]
repo = 'gmarik/vundle'
[[plugins]]
repo = 'scrooloose/nerdcommenter'
#[[plugins]]
#repo = 'thinca/vim-quickrun'
[[plugins]]
repo = 'thinca/vim-ref'
#[[plugins]]
#"repo = 'kana/vim-fakeclip'
[[plugins]]
repo = 'mattn/emmet-vim'
#[[plugins]]
#"repo = 'scrooloose/nerdtree' " from dein
#[[plugins]]
#"repo = 'vim-scripts/The-NERD-tree'
#[[plugins]]
#"repo = 'yanktmp.vim'
[[plugins]]
repo = 'vim-scripts/YankRing.vim'
[[plugins]]
repo = 'mbbill/undotree'
[[plugins]]
repo = 'kana/vim-textobj-user'
[[plugins]]
repo = 'h1mesuke/textobj-wiw'
[[plugins]]
repo = 'tpope/vim-surround'
[[plugins]]
repo = 'gcmt/wildfire.vim'
[[plugins]]
repo = 'chriskempson/base16-vim'
[[plugins]]
repo = 'othree/html5.vim'
[[plugins]]
repo = 'haya14busa/vim-migemo'
[[plugins]]
repo = 'editorconfig/editorconfig-vim'
#[[plugins]]
#repo = 'wakatime/vim-wakatime'



[[plugins]]
repo =  'itchyny/lightline.vim'
[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neocomplete'
hook_add = '  let g:neocomplete#enable_at_startup = 1'

[[plugins]]
repo = 'tomtom/tcomment_vim'
[[plugins]]
repo = 'Shougo/vimfiler'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
## vim のコマンド入力でEmacsのように option で1単語ずつ移動できるように
repo = 'houtsnip/vim-emacscommandline'

[[plugins]]
repo = 'xolox/vim-misc'
[[plugins]]
repo = 'xolox/vim-colorscheme-switcher'
depends = ['misc.vim']

[[plugins]]
# カーソル位置のコンテキストに合わせてftを切り替える
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]]
repo = 'Shougo/context_filetype.vim'
[[plugins]]
repo = 'Shougo/neco-syntax'

#[[plugins]]
### python
repo = 'davidhalter/jedi-vim'
on_ft = 'python'

[[plugins]]
## C言語用
repo =  'Rip-Rip/clang_complete'
on_ft = ["c", "cpp"]
hook_add = '''
let g:clang_library_path="/usr/local/opt/llvm/lib"
'''

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['js','javascript']

[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = ['ruby']
[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['md']
