
# カラースキーム一覧表示に Unite.vim を使う

#[[plugins]]
#repo = 'Shougo/unite.vim'
[[plugins]]
repo = 'ujihisa/unite-colorscheme'

#[[plugins]]
#repo = 'freeo/vim-kalisi'
#[[plugins]]
#repo = 'altercation/vim-colors-solarized'
#[[plugins]]
#repo = 'croaker/mustang-vim'
#[[plugins]]
#repo = 'nanotech/jellybeans.vim'
#[[plugins]]
#repo = 'vim-scripts/Lucius'
#[[plugins]]
#repo = 'vim-scripts/Zenburn'
#[[plugins]]
#repo = 'mrkn/mrkn256.vim'
#[[plugins]]
#repo = 'tomasr/molokai'
#[[plugins]]
#repo = 'daylerees/colour-schemes'
#[[plugins]]
#repo = 'chriskempson/vim-tomorrow-theme'
#[[plugins]]
#repo = 'therubymug/vim-pyte'
[[plugins]]
repo = 'Haron-Prime/Antares'
[[plugins]]
repo = 'jeffreyiacono/vim-colors-wombat'
[[plugins]]
repo = 'sickill/vim-monokai'
[[plugins]]
repo = 'google/vim-colorscheme-primary'
[[plugins]]
repo = 'sjl/badwolf'
[[plugins]]
repo = 'cocopon/iceberg.vim'
[[plugins]]
repo = 'jgdavey/vim-railscasts'
[[plugins]]
repo = 'pasela/edark.vim'
[[plugins]]
repo = 'w0ng/vim-hybrid'
